language: rust
sudo: false
cache: cargo

rust:
  - 1.31.1
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

script:
  # interleave building and testing in hope that it saves time
  # also avoid doc-testing multiple times---it takes more time and rarely helps
  - cargo build -v
  - cargo test -v
  - cargo build -v --features "handler"
