[package]
name = "algorithmia-entrypoint"
version = "0.1.0"
authors = ["Anthony Nowell <anthony@algorithmia.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syntex_syntax = "0.59.1"
syn = { version = "0.11.11", features = ["full"] }
quote = "0.3"
