(function() {var implementors = {};
implementors['algorithmia'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt; for <a class='enum' href='algorithmia/enum.AlgorithmiaError.html' title='algorithmia::AlgorithmiaError'>AlgorithmiaError</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='https://hyperium.github.io/hyper/hyper/index.html/hyper/error/enum.HttpError.html' title='hyper::error::HttpError'>HttpError</a>&gt; for <a class='enum' href='algorithmia/enum.AlgorithmiaError.html' title='algorithmia::AlgorithmiaError'>AlgorithmiaError</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='http://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/enum.DecoderError.html' title='rustc_serialize::json::DecoderError'>DecoderError</a>&gt; for <a class='enum' href='algorithmia/enum.AlgorithmiaError.html' title='algorithmia::AlgorithmiaError'>AlgorithmiaError</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='http://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/enum.EncoderError.html' title='rustc_serialize::json::EncoderError'>EncoderError</a>&gt; for <a class='enum' href='algorithmia/enum.AlgorithmiaError.html' title='algorithmia::AlgorithmiaError'>AlgorithmiaError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
